name: Docker Image CI
runs-on: 

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - name: Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
      - name: Build
        run: |
          docker build -t tmobile-nokia-clickhouse:latest .
      - name: Push
        run: |
          docker push ${{secrets.DOCKER_USER}}/tmobile-nokia-clickhouse