name: Docker Hub

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USER }}/tmobile-nokia-clickhouse:latest .
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/tmobile-nokia-clickhouse:latest